@startuml
skinparam dpi 300

actor owner as o
actor "ith account" as acc
participant "MarxCoin Network\nof registered\naccounts" as mc

o -> mc : Enables registration
acc --> mc : Registers
o -> o : Calculates the\ntarget amount\nbased on the current\nnumber of\nregistered users
o -> mc : Redistributes among network
mc --> acc : Receives share

@enduml

